### ISSUE TITLE
Windows wallet

### ISSUE THREAD

**Issue by emanbayani** [Pixocoin/Pixo-Cash#4]
Need win 64-bit wallet!

**Comment by fogoat** [comment]
I think 32-bit wallet is fine. What's the benefit with using a 64-bit wallet? I doubt you'll need more than 4GB of memory for the app. Better to use 32-bit wallet for backward compatibility.

**Comment by emanbayani** [comment]
Thank you sunk818!  The 32-bit has been outstanding!  I put the 64-bit wallet as a "to do" for a later completion!  It might be something that Pixo needs to do in the future!

**Comment by emanbayani** [comment]
I'm gonna close this as I agree with sunk818!
